config/routes.rb
Lunchzilla::Application.routes.draw do
  resource :sessions, only: [:destroy]
  resources :orders do
    resources :items, only: [:new, :create, :edit, :update]
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  root to: 'home#show'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many   :items, dependent: :destroy

  scope :current, -> {
    where(Arel::Table.new(:orders)[:created_at].gt(Date.today - 1)).
    where(Arel::Table.new(:orders)[:created_at].lt(Date.today + 1)).
    order('id ASC')
  }

  def has_item_for?(user)
    self.item_for(user).present?
  end

  def item_for(user)
    self.items.find_by(:user_id => user.id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic

  has_many :orders
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to root_path, alert: 'Please, sign in first!' unless user_signed_in?
  end

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= (User.find(session[:user_id]) if session[:user_id])
  end

  helper_method :current_user

  def user_signed_in?
    current_user
  end

  helper_method :user_signed_in?
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_order
  before_filter :find_item, only: [:edit, :update]

  def new
    @item = @order.items.build
  end

  def create
    @item = @order.items.build(item_params)
    @item.user = current_user

    if @item.save
      redirect_to orders_path(@order), notice: 'Can\'t wait!'
    else
      render action: :new
    end
  end

  def update
    if @item.update_attributes(item_params)
      redirect_to orders_path(@order), notice: 'Can\'t wait!'
    else
      render action: :edit
    end
  end


  private


  def find_order
    @order = Order.find(params[:order_id])
  end

  def find_item
    @item = current_user.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.current
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user

    if @order.save
      redirect_to action: :index, notice: "All done!"
    else
      render action: :new
    end
  end

  def update
    if @order.update_attributes(order_params)
      redirect_to action: :index, notice: "All done!"
    else
      render action: :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to action: :index, notice: "All gone! :("
  end


  private


  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:place)
  end
end

app/controllers/sessions_controller.rb
# encoding: utf-8

class SessionsController < ApplicationController
  def create
    self.current_user = User.find_or_create_by(
      github_id: auth_hash.uid,
      username:  auth_hash.info['nickname'],
      email:     auth_hash.info['email']
    )

    redirect_to orders_path, notice: "Bon appétit, #{current_user.username}!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Hope you had a good time!'
  end

  def failure
    redirect_to root_path, notice: 'Something went wrong. :( Please try again.'
  end


  protected


  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
<%= link_to orders_path do %>
  <%= image_tag 'lunch.jpg' %>
<% end %>

<p>&nbsp;</p>

<footer>
  <div class="pull-right">
    follow lunchzilla on
    <%= link_to 'github', 'https://github.com/filiptepper/lunchzilla' %>
  </div>
</footer>
</div>

app/views/items/_form.html.erb
<%= form_for [@order, @item], html: { class: 'form-horizontal well' } do |f| %>
  <fieldset>
    <legend>
      I want to order at
      <span class="label-important"><%= @order.place %></span>!
    </legend>

    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Order!', class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/new.html.erb
<%= form_for [@order, @item], html: { class: 'form-horizontal well' } do |f| %>
  <fieldset>
    <legend>
      I want to order at
      <span class="label-important"><%= @order.place %></span>!
    </legend>

    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Order!', class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lunchzilla</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">Lunchzilla</a>
          <ul class="nav">
            <li>
              <%= link_to "Orders", orders_path %>
            </li>
          </ul>
          <div class="pull-right">
            <div class="nav">
            <% if user_signed_in? -%>
              <%= link_to 'Sign out', sessions_path, method: :delete,
                class: "btn" %>
            <% else -%>
              <%= link_to 'Sign in with Github', '/auth/github',
                class: 'btn btn-primary' %>
            <% end -%>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
      <% end -%>
      <% if flash[:notice] %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
      <% end -%>

      <%= yield %>
    </div>

  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order, html: { class: 'form-horizontal well' } do |f| %>
  <fieldset>
    <legend>I want to order!</legend>

    <div class="control-group">
      <%= f.label :place, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :place %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Order!', class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/orders/edit.html.erb
<%= render 'form' %>

app/views/orders/index.html.erb
<h1>What's cooking today?</h1>

<% if @orders.any? -%>
<table class="table">
  <thead>
    <tr>
      <th>Place</th>
      <th>Who's on it?</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| -%>
    <tr>
      <td>
        <%= link_to order.place, order_path(order) %>
        <br>
        <% if order.has_item_for?(current_user) -%>
          You're having
          <%= link_to edit_order_item_path(order, order.item_for(current_user)) do -%>
            <span class="label label-success"><%= order.item_for(current_user).name %></span><% end -%>.
        <% else -%>
          You didn't order anything.
          <%= link_to 'Place', new_order_item_path(order) %> your order now!
        <% end -%>
      </td>
      <td>
        <%= order.user.username %>
      </td>
      <td>
        <%= link_to 'Edit', edit_order_path(order), class: 'label' %>
        <%= link_to 'Delete', order_path(order), class: 'label label-important', method: :delete %>
      </td>
    </tr>
    <% end -%>
  </tbody>
</table>

Want something else? Go ahead and <%= link_to "order", new_order_path %>!
<% else -%>
There's nothing on the menu today. :(
Why don't you <%= link_to "order something", new_order_path %>?
<% end -%>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/show.html.erb
<h1>
  <span class="label-success"><%= @order.place %></span> order details
</h1>

<% if @order.items.any? -%>
<table class="table">
  <thead>
    <tr>
      <th>What?</th>
      <th>Who?</th>
    </tr>
  </thead>
  <tbody>
    <% @order.items.each do |item| -%>
    <tr>
      <td>
        <%= item.name %>
      </td>
      <td>
        <%= item.user.username %>
      </td>
    </tr>
    <% end -%>
  </tbody>
</table>

<% else -%>
No orders here. :(
<% end -%>

Show me <%= link_to 'all orders', orders_path %>.